name: Build

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Create ci .env
        run: cp .env.example .env

      - name: Build & run tests via Makefile
        run: make ci