name: Build Docker Image (artifact only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the image into a local tar file (no registry push)
      - name: Build image to tar
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: flask-app:ci
          outputs: type=docker,dest=/tmp/flask-app-image.tar

      - name: Compress image
        run: gzip -9 /tmp/flask-app-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-app-image-${{ github.run_number }}
          path: /tmp/flask-app-image.tar.gz
          retention-days: 30